name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Instala dependencias
      - name: Install dependencies
        run: npm ci

      # Compila Tailwind
      - name: Build CSS with Tailwind
        run: npx tailwindcss -i ./input.css -o ./assets/output.css --minify

      # Deploy a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
