name: Deploy to cPanel (FTP)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build CSS with Tailwind
        run: npm run build

      - name: Prepare dist folder
        run: |
          rm -rf dist
          mkdir -p dist
          cp index.html dist/
          cp -r components dist/
          cp -r assets dist/
          
          # Verificar que el CSS fue compilado correctamente
          if [ ! -f dist/assets/output.css ]; then
            echo "❌ Error: output.css no se generó correctamente"
            exit 1
          fi
          echo "✅ Build completado - output.css generado"

      - name: Deploy via FTPS to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: dist/
          server-dir: '/public_html/'
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/*.zip
            .well-known/**
          log-level: standard